app/urls.py
from django.conf.urls import url
from .views import *

app_name="app"



urlpatterns=[
url(r'^$',index,name="index"),

#url(r'^(?P<posti_id>[0-9]+)/$',posti,name="posti"),
url(r'^(?P<posti_id>[0-9]+)/srulad/$',srulad,name="srulad"),
url(r'^damateba/',damateba,name="damateba"),



]

blogi/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/',include("app.urls")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^',include("sing.urls")),


]


if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sing/urls.py
from django.conf.urls import url
from .views import *

app_name="sing"



urlpatterns=[
 url(r'^$',sing_in,name="sing_in"),
 url(r'^create_account/$',create_account,name="create_account"),
 url(r'^log_out/$',log_out,name="log_out"),
 url(r'^activate/(?P<user_code>[0-9]+)/$',activate,name="activate"),
 url(r'^new_password/$',new_password.as_view(),name="new_password"),
# url(r'^(?P<posti_id>[0-9]+)/$',posti,name="posti"),
# url(r'^(?P<posti_id>[0-9]+)/srulad/$',srulad,name="srulad"),




]

app/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from datetime import datetime
# Create your models here.
class Comment(models.Model):
	#posti=models.ForeignKey(Post,on_delete=models.CASCADE,verbose_name=_("პოსტი"),null=True)
	komentari=models.CharField(verbose_name=_("კომენტარი"),max_length=200)
	def __str__(self):
		return self.komentari

	class Meta:
		verbose_name_plural=_("კომენტარები")
		verbose_name=_("კომენტარი")
class Post(models.Model):
	postis_satauri=models.CharField(verbose_name=_("სათაური"),max_length=50)
	postis_contenti=models.TextField(verbose_name=_("კონტენტი"))
	sheqmnis_dro=models.DateTimeField(verbose_name=_('შექმნის დრო'),auto_now_add=True, blank=True)
	surati=models.ImageField(verbose_name=_("სურათი"),upload_to='app')
	ganaxlebis_dro=models.DateTimeField(verbose_name=_('განახლების დრო'),auto_now_add=True, blank=True)
	comment= models.ManyToManyField(Comment,verbose_name=_("კომენტარი"))
	
	def get_medium_desc(self):
		return self.postis_contenti[:300]+" . . ."

	def get_short_desc(self):
		return self.postis_contenti[:20]+" . . ."

	def __str__(self):
		return self.postis_satauri
	class Meta:
		verbose_name_plural=_("პოსტები")
		verbose_name=_("პოსტი")

sing/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms
from .models import Comment,Post
from django.utils.translation import ugettext_lazy as _
class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['komentari']

class PostForm(forms.ModelForm):
	class Meta:
		model =Post
		fields=["postis_satauri","postis_contenti","surati"]
		

sing/forms.py
from django import forms
from django.contrib.auth.models import User


class UserUpForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput(attrs={
		'class':'pass',
		}))
	username=forms.CharField(widget=forms.TextInput(attrs={
		'class':'pass',
		'required':False,
		}))
	class Meta:
		model=User
		fields=['username','email','password']

class UserInForm(forms.Form):
	username=forms.CharField(max_length=50)
	password=forms.CharField(widget=forms.PasswordInput(attrs={
		'class':'pass',
		}))

	class Meta:
		fields=['username','password']

class New_passwordForm(forms.Form):
	password=forms.CharField(widget=forms.PasswordInput(attrs={
		'class':'pass',
		}))
	confpassword=forms.CharField(widget=forms.PasswordInput(attrs={
		'class':'pass',
		}))
	class Meta:
		fields=["password","confpassword"]

app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Post ,Comment
from .forms import CommentForm ,PostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import logout

# Create your views here.
def index(request):

	
	def my_sort(a):
		return a.comment.count()
	postebis_sia=Post.objects.all()
	popularuli_postebi=[i for i in postebis_sia]
	popularuli_postebi.sort(key=my_sort,reverse=True)
	popularuli_postebi=popularuli_postebi[:5]

	paginator = Paginator(postebis_sia, 2) # Show 2 contacts per page

	page = request.GET.get('page')
	try:
		contacts = paginator.page(page) 
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		contacts = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		contacts = paginator.page(paginator.num_pages)
	page_num=contacts.number
	postebis_sia=postebis_sia[page_num*2-2:page_num*2]

	context={
		"postebis_sia":postebis_sia,
		"popularuli_postebi":popularuli_postebi,
		"contacts":contacts,
		"user":request.user

		}
	return render(request,'app/new.html',context)


def srulad(request,posti_id):
	posti_srulad=Post.objects.get(pk=posti_id)
	form=CommentForm()
	if request.method =="POST":
		form=CommentForm(request.POST)
		if form.is_valid():
			a=form.save()
			
			posti_srulad.comment.add(a)
	context={
			"posti":posti_srulad,
			"form":form,
			"user":request.user,
			}
		
		
	return render(request,'app/srulad.html',context)

def damateba(request):
	if not request.user.is_active:
		return render(request,"app/msg_sing.html",{})	
	form=PostForm()
	if request.method=="POST":
		form=PostForm(request.POST ,request.FILES)
		if form.is_valid():
			post=form.save()
			print(post.id)
			return redirect("app:srulad",post.id)
	return render(request,'app/damateba.html',{"form":form})



		

sing/views.py
from django.shortcuts import render ,redirect
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse
from .forms import UserInForm,UserUpForm,New_passwordForm
from .util import get_code,get_id
from django.core.mail import send_mail
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth.models import User
from django.views import View
# Create your views here.
def create_account(request):
	form=UserUpForm()

	if request.method=="POST":
		form=UserUpForm(request.POST)
		if form.is_valid():
			user=form.save(commit=False)
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']
			email=form.cleaned_data['email']
			user.set_password(password)
			user.is_active=False
			user.save()




			# user=authenticate(username=username,password=password)
			
			code=get_code(user.id)
			url="http://{}/activate/{}".format(request.META['HTTP_HOST'],str(code))

			from_email = settings.EMAIL_HOST_USER
			subject="email verification"
			message='gadadit linkze tqveni account -is gasaaqtiureblad : '


			text_content = '{0}{1}'.format(message, url)
			html_content = '<p>{0}<a href="{1}">{1}</a><p>'.format(message, url)
		 
			msg = EmailMultiAlternatives(subject, text_content, from_email, [email])
			msg.attach_alternative(html_content, "text/html")
			msg.send()

			return render(request,"sing/msg_verification.html",{})

			# if user is not None:
			# 	if user.is_active:
			# 		login(request,user)
			# 		return redirect("app:index")

	return render(request,"sing/singup.html",{"form":form})



def log_out(request):
	logout(request)
	return redirect("sing:sing_in")

def sing_in(request):
	form=UserInForm(request.POST or None)
	if request.method=="POST":
		if form.is_valid():
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']

			user=authenticate(username=username,password=password)

			if user is not None:
				if user.is_active:
					login(request,user)
					return redirect("app:index")

	return render(request,"sing/singin.html",{"form":form})

def activate(request,user_code):
	user_id=get_id(int(user_code))
	user=User.objects.get(id=user_id)
	
	if user is not None:
		user.is_active=True
		user.save()
		login(request,user)
		return redirect("app:index")

	return HttpResponse("sheni imeili ver gaaqtiurda :{}".format(user_code))


class new_password(View):
	def post(self,request,*args,**kwargs):
		form=New_passwordForm(request.POST)
		if form.is_valid():
			password=form.cleaned_data['password']
			confpassword=form.cleaned_data['confpassword']
			if password==confpassword:

				user=request.user
				if user.is_active:
					user.set_password(password)
					user.save()
				else:
					return HttpResponse("პაროლი წარმატებით შეიცვალა")
			
		return HttpResponse("გთხოვთ სწორად შეავსოთ ველები .. ")

	def get(self,request,*args,**kwargs):
		form=New_passwordForm()
		context={
		"form":form,
		"user":request.user
		}
		return render(request,"sing/new_password.html",context)

sing/templates/sing/sing_in.html
<!DOCTYPE html>
<html >
<head>
  {% load static %}
  <meta charset="UTF-8">
  <title>გამარობათ !</title>
  <link href='http://fonts.googleapis.com/css?' family='Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  
      <link rel="stylesheet" href="{% static 'css/style.css' %}">

  
</head>

<body>
  <div class="form">
      
      <ul class="tab-group">
        <li class="tab active"><a href="#signup">რეგისტრაცია</a></li>
        <li class="tab"><a href="#login">შესვლა</a></li>
      </ul>
      
      <div class="tab-content">
        <div id="signup">   
          <h1>კეთილი იყოს თქვენი მობრძანება</h1>
          
          <form action="app/" method="POST">
          {% csrf_token %}
          <div class="top-row">
            <div class="field-wrap">
              <label>
                სახელი<span class="req">*</span>
              </label>
              <input type="text" name="user_saxeli" value="{{form1.saxeli}}" required autocomplete="off" />
            </div>
        
            <div class="field-wrap">
              <label>
                გვარი<span class="req">*</span>
              </label>
              <input type="text"required name="user_gvari" value="{{form1.gvari}}" autocomplete="off"/>
            </div>
          </div>

          <div class="field-wrap">
            <label>
              იმეილი<span class="req">*</span>
            </label>
            <input type="email"required name="user_email" value="{{form1.email}}" autocomplete="off"/>
          </div>
          
          <div class="field-wrap">
            <label>
              პაროლი<span class="req">*</span>
            </label>
            <input type="password"required name="user_password" value="{{form1.password}}" autocomplete="off"/>
          </div>
          
          <button type="submit" class="button button-block"/>დარეგისტრირება</button>
          
          </form>

        </div>
        
        <div id="login">   
          <h1>კეთილი იყოს თქვენი დაბრუნება</h1>
          
          <form action="app/" method="POST">
          {% csrf_token %}
            <div class="field-wrap">
            <label>
              იმეილი<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>
          
          <div class="field-wrap">
            <label>
              პაროლი<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>
          
          <p class="forgot"><a href="app/">დაგავიწყდათ პაროლი?</a></p>
          
          <button class="button button-block"/>შესვლა</button>
          
          </form>

        </div>
        
      </div><!-- tab-content -->
      
</div> <!-- /form -->
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script src="{% static 'js/index.js' %}"></script>

</body>
</html>

templates/app/damateba.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
	<title>{% trans "პოსტის დამატება" %}</title>
</head>
<body>
 <form action="" method="POST" enctype='multipart/form-data'>
 {% csrf_token %}
 	{{ form.as_p}}

	<input type="submit" value= "{% trans 'დამატება' %}">
</body>
</html>

templates/app/index.html
<!DOCTYPE html>
<html>
<head>
	{% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />

</head>
<body>

{% if postebis_sia %}
	<ul>
	{% for object in postebis_sia %}
		<p>{{object.postis_satauri}}</p>
		<p>{{object.get_short_desc}}</p>
		<img src="{{object.surati.url}}" style="width:304px;height:228px;">

		<a type="button" href="{% url 'app:srulad' object.id %}" >სრულად</a>
	{% endfor %}
	</ul>
	

{% else %}
	<p>ბლოგი მიუწვდომელია</p>
{% endif %}
</body>
</html>

templates/app/lang_change.html
{% load i18n %}
<div style="height: 70px;">
	<form action="/i18n/setlang/" method="POST" style="float: right; display: inline-block;">
		{% csrf_token %}
		<div>
			<li style="text-decoration: none;list-style: none;">
				<button id="geo" type="submit" value="ka"  name="language" > </button>
			</li>
			<li style="text-decoration: none;list-style: none;">
				<button id="eng" type="submit" value="en"  name="language" ></button>
			</li>
		</div>
   </form>
</div>

templates/app/log_out.html
{% load i18n %}
{%if  user.is_active%}
<p id="log_out">
	<a  href="{% url 'sing:log_out' %}" ">{% trans 'გასვლა' %}</a>
</p>
{% else %}
<p id="log_in">
	<a  href="{% url 'sing:sing_in' %}">{% trans 'შესვლა' %}</a>
</p>
{% endif %}

templates/app/msg_sing.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
	<title>| :( |</title>
</head>
<body>

<p>{% trans 'პოსტი დასამატებლად გაიარეთ' %}<a href="{% url 'sing:sing_in' %}">
{% trans 'ავტორიზაცია' %}</a>

</body>
</html>

templates/app/new.html
{% load i18n %}
<!DOCTYPE html>
<html>
<title>{% trans "ბლოგი" %}</title>
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/new.css' %}">

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>
<body class="w3-light-grey">

<!-- w3-content defines a container for fixed size centered content, 
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1400px">

<!-- Header -->
<header class="w3-container w3-center w3-padding-32"> 
  <h1><b>MY BLOG</b></h1>
  <p>Welcome to the blog of <span class="w3-tag">{% trans "ცოტნე შარვაძე" %}</span></p>

  {% include "app/lang_change.html" %}
{% include "app/log_out.html" %}
{% include "app/welcome_person.html" %}
{% include "app/postis_damateba.html" %}
</header>


<!-- Grid -->
<div class="w3-row">

<!-- Blog entries -->
<div class="w3-col l8 s12">
  {% for object in postebis_sia %}
  <!-- Blog entry -->
  <div class="w3-card-4 w3-margin w3-white">
    <img src="{{object.surati.url}}" alt="Nature" style="width: 100%; height: 400px;">
    <div class="w3-container w3-padding-8">
      <h3><b>{{object.postis_satauri}}</b></h3>
      <h5>{% trans "განთავსების დრო" %} : <span class="w3-opacity">{{ object.sheqmnis_dro }}</span></h5>
    </div>

    <div class="w3-container">
      <p>{{object.get_medium_desc}}</p>
      <div class="w3-row">
        <div class="w3-col m8 s12">
          <p><a type="button" href="{% url 'app:srulad' object.id %}"  class="w3-btn w3-padding-large w3-white w3-border w3-hover-border-black"><b>{% trans "სრულად" %}»</b></a></p>
        </div>
        <div class="w3-col m4 w3-hide-small">
          <p><span class="w3-padding-large w3-right"><b>{% trans "კომენტარები" %} </b> <span class="w3-tag">{{object.comment.count}}</span></span></p>
        </div>
      </div>
    </div>
  </div>
  <hr>
  {% endfor %}
<!-- END BLOG ENTRIES -->
</div>
<!-- Introduction menu -->
<div class="w3-col l4">

  <!-- About Card -->
  <div class="w3-card-2 w3-margin w3-margin-top">
  <img src="{% static 'img/prof.jpg' %}" style="width: 100%; height: 450px;">
    <div class="w3-container w3-white">
      <h4><b>{% trans "ცოტნე შარვაძე" %}</b></h4>
      <p>{% trans "მე ვარ ცოტნე შარვაძე დავბადე 1997 წლის 23 მარტს,თბილისში.პროფესიით ვარ პროგრამისტი , ამიტომაც მიწევს ბლგის შექმნა თორე ჩემით ამას არ ვიზავდი , ნუ არც მაძალებენ , მომწონს კიდეც .ამდენი იმიტომ ვიბოდიალე რომ დიდი ტექსტი მჭირდებოდა .. "%}</p>
    </div>
  </div><hr>
  
  <!-- Posts -->
  <div class="w3-card-2 w3-margin">
    <div class="w3-container w3-padding">
      <h4>{% trans "პოპულარული პოსტები" %}:</h4>
    </div>
    {% for i in popularuli_postebi %}
    <ul class="w3-ul w3-hoverable w3-white"><a  href="{% url 'app:srulad' i.id %}">
      <li class="w3-padding-16">
        <img src="{{i.surati.url}}" alt="Image" class="w3-left w3-margin-right" style="width:50px;height: 50px">
        <span class="w3-large">{{i.postis_satauri}}</span><br>
        <span>{{i.get_short_desc}}</span>
      </a>
      </li>
    </ul>
    {% endfor %}
  </div>
  <hr> 
 <!---->
  <!-- Labels / tags -->
  <div class="w3-card-2 w3-margin">
    <div class="w3-container w3-padding">
      <h4>Tags</h4>
    </div>
    <div class="w3-container w3-white">
    <p><span class="w3-tag w3-black w3-margin-bottom">Travel</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">New York</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">London</span>
      <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">IKEA</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">NORWAY</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">DIY</span>
      <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Ideas</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Baby</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Family</span>
      <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">News</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Clothing</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Shopping</span>
      <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Sports</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Games</span>
    </p>
    </div>
  </div>
  
<!-- END Introduction Menu -->
</div>

<!-- END GRID -->
</div><br>

<!-- END w3-content -->
</div>

<!-- Footer -->
<footer class="w3-container w3-dark-grey w3-padding-32 w3-margin-top">
    <div class="pagination">
      <span class="step-links">
          {% if contacts.has_previous %}
              <a class="w3-btn w3-padding-large w3-margin-bottom" href="?page={{ contacts.previous_page_number }}">{% trans "წინ" %}</a>
          {% endif %}

          <span class="current">
              {% trans "გვერდი" %}: {{ contacts.number }} / {{ contacts.paginator.num_pages }} .
          </span>

          {% if contacts.has_next %}
              <a class="w3-btn w3-padding-large w3-margin-bottom" href="?page={{ contacts.next_page_number }}">{% trans "შემდეგი" %}»</a>
          {% endif %}
      </span>
  </div>
  <!-- <button class="w3-btn w3-disabled w3-padding-large w3-margin-bottom">წინ </button> -->
<!--   <button class="w3-btn w3-padding-large w3-margin-bottom">წინ </button>
  <button class="w3-btn w3-padding-large w3-margin-bottom">შემდეგი »</button> -->
  <p>{% trans "შექმნიალია  :" %}<a href="https://www.facebook.com/tsotnesharvadze" target="_blank">ts.sharvadze</a>{% trans "-ის მიერ" %}</p>

</footer>

</body>
</html>

templates/app/postis_damateba.html
{% load i18n %}
{%if  user.is_staff%}
<p id="damateba">
	<a  href="{% url 'app:damateba' %}">{% trans 'პოსტის დამატეაბა' %}</a>
</p>
{% endif %}

templates/app/srulad.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
<link rel="stylesheet" href="{% static 'css/new.css' %}">
<!-- <style>
body {background-color: powderblue;}
h1   {color: blue;}
p    {color: red;}
</style> -->
</head>
<body style="background-color: rgb(191, 191, 191);">
{% include "app/lang_change.html" %}
	<p style="text-align: center;" >{{posti.postis_satauri}}</p>
	<img src="{{posti.surati.url}}" alt="some_text" style="width: 1000px; height: 400px; margin: auto; display: block; border-radius: 10px;">

	<p style="text-align: center; line-height: 2.5em; display: block; margin: auto; width: 1024px;">{{posti.postis_contenti}}</p>

	<p style="display: block; padding-left: 18%; color: rgb(34, 34, 34);">{{posti.sheqmnis_dro}}</p>
	{% for i in posti.comment.all %}
		<p style="padding-left: 6%;">{{i}}</p>
	{% endfor %} 

{%if user.is_active%}
 <form action="" method="POST" >
 {% csrf_token %}
 	{{ form.as_p}}
	<!-- <label for="new_comment">ახალი კომენტარი :</label>
	<input id="new_comment" type="text" name="new_comment" maxlength="100" value ="{{ form.komentari}}"required /> -->
	<input type="submit" value= 'OK'>
</form>
{%endif%}
</body>
</html>

templates/app/welcome_person.html
{% if user.is_active %}
<p id="person">
	welcome : {{ user }}
</p>
{% endif %}

templates/lang_change.html
{% extand new.html %}
{% load i18n %}
{% block language %}
<form action="/i18n/setlang/" method="POST" style="float: right; display: inline-block;">
	<div>
		<li>
			<button id="geo" type="submit"> </button>
		</li>
		<li>
			<button id="eng" type="submit"></button>
		</li>
	</div>
</form>
{% endblock language %}

templates/sing/base.html
<!DOCTYPE html>
<html>
<head>
	<title>კეთილი იყოს თქვენი მობრძანება </title>
  
</head>
<body>

			{% block sing_up %}
			{% endblock sing_up %}
			{% block sing_in %}
			{% endblock sing_in %}
			{% block new_password %}
			{% endblock new_password %}
			{% block msg_verification %}
			{% endblock msg_verification %}

</body>
</html>

templates/sing/msg_verification.html
{% extends "sing/base.html" %}
{% load i18n %}

{% block msg_verification %}
<p>{%trans 'თქვენი ექაუნთის გასააქტიურებლად შეამოწმეთ ' %}<a type="button" href="https://mail.google.com/"  class="w3-btn w3-padding-large w3-white w3-border w3-hover-border-black"><b>{% trans "იმეილი" %}»</b></a></p>


{% endblock msg_verification %}

templates/sing/new_password.html
{% extends 'sing/base.html' %}
{% load i18n %}


{% block new_password %}
{% if user.is_active %}
<form method="POST", action="">
 {% csrf_token %}
{{form.as_p}}
<input type="submit" value= "{% trans 'შეცვლა' %}">
</form>
{% endif %}
{% endblock new_password %}

templates/sing/sing1.html
<!DOCTYPE html>
<html>
<head>
	<title>iftf</title>
	 {% load static %}
  <meta charset="UTF-8">
  <title>გამარობათ !</title>
  <link href='http://fonts.googleapis.com/css?' family='Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  
      <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<div class="form">
    <ul class="tab-group">
        <li class="tab active"><a href="#signup">რეგისტრაცია</a></li>
        <li class="tab"><a href="#login">შესვლა</a></li>
     </ul>
      
    <div class="tab-content">
        <div id="signup">   
          <h1>კეთილი იყოს თქვენი მობრძანება</h1>
				<form method="POST" action="" >
				{% csrf_token %}
				<div class="top-row">
				{{form.as_p}}
				</div>
				<button type="submit" class="button button-block"/>დარეგისტრირება</button>
				</form>
		</div>
        
        <div id="login">   
          <h1>კეთილი იყოს თქვენი დაბრუნება</h1>
          
          <form action="" method="POST">
          {% csrf_token %}
            <div class="field-wrap">
            <label>
              იმეილი<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>
          
          <div class="field-wrap">
            <label>
              პაროლი<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>
          
          <p class="forgot"><a href="app/">დაგავიწყდათ პაროლი?</a></p>
          
          <button class="button button-block"/>შესვლა</button>
          
          </form>

        </div>
        
    </div><!-- tab-content -->
      
</div> <!-- /for

  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script src="{% static 'js/index.js' %}"></script>

</body>
</html>

templates/sing/singin.html
{% extends "sing/base.html" %}

{% block sing_in %}
<form  action="" method="POST">{% csrf_token %}
	{{form.as_p}}

<button class="button button-block"/>შესვლა</button>

</form>

<a href="{% url 'sing:create_account' %}"><button class="button button-block"/>დარეგისტრირება</button></a>

{% endblock sing_in %}

templates/sing/singup.html
{% extends "sing/base.html" %}

{% block sing_up %}
<form  action="" method="POST">{% csrf_token %}
	{{form.as_p}}

<button type="submit" class="button button-block"/>დარეგისტრირება</button>

</form>



{% endblock sing_up %}